// Generated by CoffeeScript 1.7.1
(function() {
  var print, print2;

  print = function(a, b, c, d, e, x, y, z) {
    console.log("IF\n" + "\t 'Matrix Intersect - All Numeric'(");
  };


  /*
  'TransactionChars.First Score'
  'TransactionChars.Amount'
  'TransactionChars.New Limit'
   */

  print2 = function(a, b, c, d, e) {
    print(a, b, c, d, e, "'TransactionChars.First Score'", "'TransactionChars.Amount'", "'TransactionChars.New Limit'");
  };

  print2("0", "580", "0", "hi", "0");

}).call(this);
