// Generated by CoffeeScript 1.7.1
(function() {
  var array, print, print2, x, _i, _len;

  print = function(a, b, c, d, e, x, y, z) {
    console.log("IF\n" + "\t 'Matrix Intersect - All Numeric'(", x + ", " + a + ", " + b + ", " + y + ", " + c + ", " + d + ") = 1 \nTHEN\n\t" + z + " = " + e + "\nENDIF");
  };


  /*
  'TransactionChars.First Score'
  'TransactionChars.Amount'
  'TransactionChars.New Limit'
   */

  print2 = function(a, b, c, d, e) {
    print(a, b, c, d, e, "'TransactionChars.First Score'", "'TransactionChars.Amount'", "'TransactionChars.New Limit'");
  };

  array = [["0", "580", "0", "99999", "0"], ["0", "580", "0", "99999", "0"]];

  for (_i = 0, _len = array.length; _i < _len; _i++) {
    x = array[_i];
    print2(x[0], x[1], x[2], x[3], x[4]);
    console.log("\n\n\n");
  }

}).call(this);
